apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: myapp
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n 'admin' | base64 => YWRtaW4=
  # echo -n 'P@ssw0rd123' | base64 => UEBzc3cwcmQxMjM=
  username: YWRtaW4=
  password: UEBzc3cwcmQxMjM=
  api_key: bXktc2VjcmV0LWFwaS1rZXktMTIzNDU2Nzg5MA==
